version: 0.2

phases:
  install:
    commands:
      # - echo installing nvm...
      # - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      # - export NVM_DIR="$HOME/.nvm"
      # - "[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh""
      # - nvm install 14.17.3
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      # install the typescript compiler
      - npm i -g tsc
  build:
    commands:
      # build the ts into js
      - tsc -p .
artifacts:
  files: 
    - build/**/*
    - package.json
    - package-lock.json
  discard-paths: no
  base-directory: build/