version: 0.2

phases:
  install:
    commands:
      - echo installing nvm...
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
       - . ~/.nvm/nvm.sh
      - echo installing node-14.17.3
      - nvm install node 14.17.3
  pre_build:
    commands:
      # install the typescript compiler
      - npm i -g tsc
  build:
    commands:
      # build the ts into js
      - tsc -p .
artifacts:
  files: 
    - build/**/*
    - package.json
    - package-lock.json
  discard-paths: no
  base-directory: build/