version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      # install the typescript compiler
      - npm i typescript
  build:
    commands:
      # build the ts into js
      - npx tsc -p .
artifacts:
  files: 
    - build/**/*
    - package.json
    - package-lock.json
  discard-paths: no